### ISSUE TITLE
Phpmyadmin

### ISSUE THREAD

**Issue by Bugsbane** [uboslinux/apps-wanted#34]
For users like me who are looking for an easier way to host and maintain a server, Phpmyadmin makes many maintenance functions (especially in the moving of sites using databases) far, far easier than trying to use Mariadb only through the commandline.

**Comment by jernst** [comment]
UBOS is designed so that nobody ever needs to interact with a database directly. So we have no intention of making database administration more user-friendly ;-)

**Comment by Bugsbane** [comment]
Uh, OK.... So if I want to migrate my nextcloud instance over to UBOS, what's the best way of doing that? Normally I'd set up an install of Nextcloud, them copy the files over, then use Phpmyadmin to bring over the database. What's the UBOS way of doing things here?

**Comment by jernst** [comment]
What we really should have (but currently don't ... would you like to write it? :-)) is a little script that can produce a `.ubos-backup` file from a non-UBOS Nextcloud instance. Once you have that file, you say `ubos-admin restore --in my.ubos-backup` on a clean UBOS system and you have your Nextcloud instance all up and running with your data in it.

The file format is documented, the perhaps easiest way of seeing how it work is to setup a new site with the apps you want, `ubos-admin backup`, and examine what's in the file -- it's just a zip file with some extra metadata and conventions.

**Comment by Bugsbane** [comment]
Given that I know basically no coding at all (does BASIC from when I was a kid count?) it sounds like my best option is just to export the SQL file and import it in the client directly into MariaDB.

I do like the idea of having an UBOS export app in nextcloud and doing it the way you suggested. It would just likely take me at least two months to figure out how to code well enough to create that. Ask me to design a logo, write marketing copy or edit a sales video though, and you may have better luck. ;-) Thanks for explaining though!

**Comment by Bugsbane** [comment]
Er, "client" was autocorrect changing what I typed from "CLI"
