### ISSUE TITLE
Spreed.me

### ISSUE THREAD

**Issue by Bugsbane** [uboslinux/apps-wanted#35]
The secure video / audio / chat app being integrated into Nextcloud. A separate spreed server is still required to Nextcloud to access, plus there is a Spreed Nextcloud app to integrate the two.

This ticket is for the Spreed.me server + the Spreed Nextcloud app

**Comment by jernst** [comment]
That'd be good. Would you like to take a stab at it?

**Comment by Bugsbane** [comment]
Actually, I just read that with nextcloud 11, that a Spreed server may no longer be necessary for standard voice/audio calls or text chat. Apparently the Spreed server is now only needed for some advanced stuff like screensharing. I'd want to test, but if this is accurate, then this request might not actually be needed after all.

**Comment by jernst** [comment]
Please do report back the result of your investigation / test.

**Comment by jernst** [comment]
We have the plugin, so we should be fine.
