### ISSUE TITLE
Mastodon

### ISSUE THREAD

**Issue by klundry** [uboslinux/apps-wanted#46]
Mastodon is a federated and self-hostable social networking/microblogging platform.

**Comment by jernst** [comment]
I started working on this actually :-) but haven't had enough time.

**Comment by klundry** [comment]
Great! I think it would be great if ubos had a presence on mastodon as well :). There are a lot of like minded people into programming/open source/selfhosting over there. I think it would be a good place to try to find some more interest and possibly contributers.

**Comment by jernst** [comment]
Initial version created: https://github.com/uboslinux/ubos-mastodon . Will be available with the next app update. P.S. It supposedly is a resource hog.
