### ISSUE TITLE
Pi-hole

### ISSUE THREAD

**Issue by xNeo92x** [uboslinux/apps-wanted#60]

**Comment by jernst** [comment]
The Arch port of Pi-hole apparently [requires](https://wiki.archlinux.org/index.php/Pi-hole) a forked version of `dnsmasq`, and conflicts with the original. This seems a bit of a support nightmare, and so we'll only consider this as a core UBOS package if somebody has demonstrated to make it work well on UBOS devices run as routers (netconfig `gateway` and the like).
