### ISSUE TITLE
Nextcloud app:  Auto Mail Accounts 

### ISSUE THREAD

**Issue by moretocome** [uboslinux/apps-wanted#69]
The Nextcloud app:  [Auto Mail Accounts](https://apps.nextcloud.com/apps/auto_mail_accounts) greatly simplifies new account creation in Nextcloud fro organisations by allowing the admin to preconfigure the default user mail accounts with the mail and smtp server settings from the hosting provider. The users then only need to enter their usernames and passwords to read and send emails from Nextcloud.

**Comment by jernst** [comment]
In the pipeline.
