### ISSUE TITLE
Nextcloud app: Passwords

### ISSUE THREAD

**Issue by moretocome** [uboslinux/apps-wanted#72]
The Nextcloud app: [Passwords](https://apps.nextcloud.com/apps/passwords) adds password sync and sharing to Nextcloud.

**Comment by jernst** [comment]
Probably the link should be: https://apps.nextcloud.com/apps/passwords

**Comment by moretocome** [comment]
Yes of course, thank you! Have updated the original post :)

**Comment by jernst** [comment]
﻿﻿Added with the latest UBOS update.
