### ISSUE TITLE
Nextcloud app:  Community Document Server 

### ISSUE THREAD

**Issue by moretocome** [uboslinux/apps-wanted#84]
Upcomming Nextcloud 18 features an internal OnlyOffice document server, and I would be very interested in that.

https://apps.nextcloud.com/apps/documentserver_community

**Comment by jernst** [comment]
Working on it: https://github.com/uboslinux/ubos-app-nextcloud/tree/develop/nextcloud-documentserver-community --if all goes well, should be part of the next apps update.
