### ISSUE TITLE
Jitsi

### ISSUE THREAD

**Issue by fschaap** [uboslinux/apps-wanted#9]
Jitsi does a lot and can also function as a Hangouts/Skype replacement. It has Arch packages. https://jitsi.org/

**Comment by uboslinux** [comment]
Does Jitsi require a desktop environment? UBOS is really for servers ...
(Also, the link to the Arch Linux packages produces a 404)

**Comment by fschaap** [comment]
I figured there must be a server based component, because of this implementation: https://jitsi.tools.ietf.org/ but now I'm not so sure... just a bunch of javascript libraries it would appear. That would be cool to host yourself too though :-)

As for the Arch packages, there are two other Jitsi repositories. One is old and not updated, the other nightly. And besides, looks like a desktop implementation of Jitsi, not server based. So  that's not the way to go.
