### ISSUE TITLE
Nextcloud 6.4.2

### ISSUE THREAD

**Issue by teledyn** [uboslinux/apps-wanted#90]
The Nextcloud is really nice in a home cloud, but is rather outdated.  What is the process for porting an application like Nextcloud (or Peertube etc) to be acceptable for UBOS to install as a site?

**Comment by teledyn** [comment]
Possibly related to this but I didn't know where else to mention it, the _current_ version of the Nextcloud app has a help system, but for adding external storage, it only says

> The External Storage application allows you to mount external storage services, such as Amazon S3, SMB/CIFS file servers and FTP servers… in Nextcloud. Your Nextcloud server administrator controls which of these are available to you. Please see [Configuring External Storage (GUI)](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html) in the Nextcloud Administrator’s manual for configuration how-tos and examples.

but the advice on the Configuration External Storage link describe options we just don't have in our current Nextcloud.

**Comment by teledyn** [comment]
Within the Nextcloud App on the Raspberry Pi4 release there is an alert to upgrade to version "26.0.7" which I can download as a zip file, but the button to "Open Updater" won't find the occ. Is it possible to install this zip file?

**Comment by jernst** [comment]
Updated version is in the repo, https://github.com/uboslinux/ubos-app-nextcloud/blob/develop/nextcloud/PKGBUILD for now you need to build and install yourself (git checkout, `makepkg`, then `ubos-admin update --pkg <pkgfile>`.)

All documented in https://ubos.net/docs/developers
